/* QUESTION */
export const GET_QUESTION_MESSAGES_PENDING = 'GET_QUESTION_MESSAGES_PENDING';
export const GET_QUESTION_MESSAGES_SUCCESS = 'GET_QUESTION_MESSAGES_SUCCESS';
export const GET_QUESTION_MESSAGES_ERROR = 'GET_QUESTION_MESSAGES_ERROR';

export const GET_QUESTION_MESSAGE_PENDING ='GET_QUESTION_MESSAGE_PENDING';
export const GET_QUESTION_MESSAGE_SUCCESS ='GET_QUESTION_MESSAGE_SUCCESS';
export const GET_QUESTION_MESSAGE_ERROR = 'GET_QUESTION_MESSAGE_ERROR';

/* ANSWERS */
export const GET_ANSWERS_MESSAGES_PENDING = 'GET_ANSWERS_MESSAGES_PENDING';
export const GET_ANSWERS_MESSAGES_SUCCESS = 'GET_ANSWERS_MESSAGES_SUCCESS';
export const GET_ANSWERS_MESSAGES_ERROR = 'GET_ANSWERS_MESSAGES_ERROR';

export const GET_ANSWERS_MESSAGE_PENDING = 'GET_ANSWERS_MESSAGE_PENDING';
export const GET_ANSWERS_MESSAGE_SUCCESS = 'GET_ANSWERS_MESSAGE_SUCCESS';
export const GET_ANSWERS_MESSAGE_ERROR = 'GET_ANSWERS_MESSAGE_ERROR';

/* UPVOTE */
export const UPVOTE_ANSWERS_PENDING = 'UPVOTE_ANSWERS_PENDING';
export const UPVOTE_ANSWERS_SUCCESS = 'UPVOTE_ANSWERS_SUCCESS';
export const UPVOTE_ANSWERS_ERROR = 'UPVOTE_ANSWERS_ERROR';

/* DOWNVOTE */
export const GET_DOWNVOTE_PENDING = 'GET_DOWNVOTE_PENDING';
export const GET_DOWNVOTE_SUCCESS = 'GET_DOWNVOTE_SUCCESS';
export const GET_DOWNVOTE_ERROR = 'GET_DOWNVOTE_ERROR';

/* COMMENTS */
export const GET_COMMENT_PENDING = 'GET_COMMENT_PENDING';
export const GET_COMMENT_SUCCESS = 'GET_COMMENT_SUCCESS';
export const GET_COMMENT_ERROR = 'GET_COMMENT_ERROR';

export const GET_COMMENTS_PENDING = 'GET_COMMENTS_PENDING';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_ERROR = 'GET_COMMENTS_ERROR';
