/* QUESTION */
export const GET_QUESTION_MESSAGES_PENDING = 'GET_QUESTION_MESSAGES_PENDING';
export const GET_QUESTION_MESSAGES_SUCCESS = 'GET_QUESTION_MESSAGES_SUCCESS';
export const GET_QUESTION_MESSAGES_ERROR = 'GET_QUESTION_MESSAGES_ERROR'

export const GET_QUESTION_MESSAGE_PENDING ='GET_QUESTION_MESSAGE_PENDING';
export const GET_QUESTION_MESSAGE_SUCCESS ='GET_QUESTION_MESSAGE_SUCCESS';
export const GET_QUESTION_MESSAGE_ERROR = 'GET_QUESTION_MESSAGE_ERROR';

/* ANSWERS */
export const GET_ANSWERS_MESSAGES_PENDING = 'GET_ANSWERS_MESSAGES_PENDING';
export const GET_ANSWERS_MESSAGES_SUCCESS = 'GET_ANSWERS_MESSAGES_SUCCESS';
export const GET_ANSWERS_MESSAGES_ERROR = 'GET_ANSWERS_MESSAGES_ERROR';

export const GET_ANSWERS_MESSAGE_PENDING = 'GET_ANSWERS_MESSAGE_PENDING';
export const GET_ANSWERS_MESSAGE_SUCCESS = 'GET_ANSWERS_MESSAGE_SUCCESS';
export const GET_ANSWERS_MESSAGE_ERROR = 'GET_ANSWERS_MESSAGE_ERROR'